name: Deploy Frontend to Firebase Hosting

on:
  push:
    branches: [ main ]
    paths:
      - "public/**"
      - "firebase.json"
      - ".firebaserc"
      - ".github/workflows/deploy-frontend.yml"
      # add your real build output or app code paths here if you build:
      # - "src/**" - "package.json" - "vite.config.*" - "next.config.*"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # If you have a JS build (Vite/Next/React), keep this block and build.
      # If you’re only serving /public, you can delete this whole Node block.
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install & Build (skip if no package.json)
        if: ${{ hashFiles('**/package.json') != '' }}
        run: |
          npm ci || npm install
          npm run build || echo "No build script, skipping"

      - name: Deploy to Firebase Hosting (production)
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_NEUROCARTAI }}"
          channelId: live
          projectId: neurocartai-467717
