jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      # ⬇️ bump Node to 22 (or 20)
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'   # optional but nice

      - name: Install Dependencies
        run: |
          if [ -f package.json ]; then npm ci || npm install; fi

      - name: Build Project
        run: |
          if [ -f package.json ]; then npm run build || true; fi

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_NEUROCARTAI }}"
          channelId: live
          projectId: neurocartai-467717
